/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdvanceCertification: typeof import('./src/components/Forms/AdvanceCertification/index.vue')['default']
    Certification: typeof import('./src/components/Forms/Certification/index.vue')['default']
    CoinsTable: typeof import('./src/components/Common/CoinsTable/index.vue')['default']
    DataTable: typeof import('./src/components/Common/DataTable/index.vue')['default']
    Drawer: typeof import('./src/components/Common/Drawer/index.vue')['default']
    FundsDetails: typeof import('./src/components/History/FundsDetails/index.vue')['default']
    HomeMenu: typeof import('./src/components/Home/HomeMenu/index.vue')['default']
    Language: typeof import('./src/components/Common/Language/index.vue')['default']
    MobileNav: typeof import('./src/components/Common/MobileNav/index.vue')['default']
    NavBar: typeof import('./src/components/Common/NavBar/index.vue')['default']
    Recharge: typeof import('./src/components/History/Recharge/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/Common/Select/index.vue')['default']
    Support: typeof import('./src/components/Common/Support/index.vue')['default']
    Swiper: typeof import('./src/components/Home/Swiper/index.vue')['default']
    TopCoin: typeof import('./src/components/Common/TopCoin/index.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCheckboxGroup: typeof import('vant/es')['CheckboxGroup']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanNoticeBar: typeof import('vant/es')['NoticeBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanUploader: typeof import('vant/es')['Uploader']
    Withdraw: typeof import('./src/components/History/Withdraw/index.vue')['default']
  }
}
